const Guidelines = require("../model/Guidelines");

const LOGCONSTANTS = {
  actions: {
    user: {
      CREATE_USER: "CREATE USER",
      LOGIN: "LOGIN",
      LOGOUT: "LOGOUT",
      DELETE_USER: "DELETE USER"
    },
    achievements: {
      CREATE_ACHIEVEMENT: "CREATE ACHIEVEMENT",
      UPDATE_ACHIEVEMENT: "UPDATE ACHIEVEMENT",
      DELETE_ACHIEVEMENT: "DELETE ACHIEVEMENT",
    },
    guidelines: {
      CREATE_GUIDELINE: "CREATE GUIDELINE",
      UPDATE_GUIDELINE: "UPDATE GUIDELINE",
      DELETE_GUIDELINE: "DELETE GUIDELINE",
    },
    materials: {
      CREATE_MATERIAL: "CREATE MATERIAL",
      UPDATE_MATERIAL: "UPDATE MATERIAL",
      DELETE_MATERIAL: "DELETE MATERIAL"
    },
    news: {
      CREATE_NEWS: "CREATE NEWS",
      UPDATE_NEWS: "UPDATE NEWS",
      DELETE_NEWS: "DELETE NEWS",
    },
    officials: {
      CREATE_OFFICIAL: "CREATE OFFICIAL",
      UPDATE_OFFICIAL: "UPDATE OFFICIAL",
      DELETE_OFFICIAL: "DELETE OFFICIAL",
    },
    pageContents: {
      CREATE_PAGE_CONTENTS: "CREATE PAGE CONTENTS",
      UPDATE_PAGE_CONTENTS: "UPDATE PAGE CONTENTS",
    },
    products: {
      CREATE_PRODUCT: "CREATE PRODUCT",
      UPDATE_PRODUCT: "UPDATE PRODUCT",
      DELETE_PRODUCT: "DELETE PRODUCT",
    },
    records: {
      CREATE_RECORD: "CREATE RECORD",
      UPDATE_RECORD: "UPDATE RECORD", 
    },
    skills: {
      CREATE_SKILLS: "CREATE SKILLS",
      UPDATE_SKILLS: "UPDATE SKILLS",
      DELETE_SKILLS: "DELETE SKILLS",
    },
    farms: {
      CREATE_FARM: "CREATE FARM",
      UPDATE_FARM: "UPDATE FARM",
      DELETE_FARM: "DELETE FARM"
    }
  },
  categories: {
    CONTENT_MANAGEMENT: "CONTENT MANAGEMENT",
    AUTHENTICATION: "AUTHENTICATION",
    INVENTORY: "INVENTORY",
    RECORD_MANAGEMENT: "RECORD MANAGEMENT",
    USER_MANAGEMENT: "USER MANAGEMENT",
    GREEN_PAGE: "GREEN PAGE"
  },
  targetTypes: {
    ACHIEVEMENT: "ACHIEVEMENT",
    USER: "USER",
    FARM: "FARM",
    GUIDELINE: "GUIDELINE",
    MATERIAL: "MATERIAL",
    NEWS: "NEWS",
    RECORD: "RECORD",
  }
};


module.exports = {LOGCONSTANTS};