export const LOGCONSTANTS = {
  actions: {
    user: {
      CREATE_USER: "CREATE USER",
      LOGIN: "LOGIN",
      LOGOUT: "LOGOUT"
    },
    achievements: {
      CREATE_ACHIEVEMENT: "CREATE ACHIEVEMENT",
      UPDATE_ACHIEVEMENT: "UPDATE ACHIEVEMENT",
      DELETE_ACHIEVEMENT: "DELETE ACHIEVEMENT",
    },
  },
  categories: {
    CONTENT_MANAGEMENT: "CONTENT MANAGEMENT",
    AUTHENTICATION: "AUTHENTICATIon"
  },
};
