export const LOGCONSTANTS = {
  actions: {
    user: {
      CREATE_USER: "CREATE USER",
      LOGIN: "LOGIN",
      LOGOUT: "LOGOUT",
    },
    achievements: {
      CREATE_ACHIEVEMENT: "CREATE ACHIEVEMENT",
      UPDATE_ACHIEVEMENT: "UPDATE ACHIEVEMENT",
      DELETE_ACHIEVEMENT: "DELETE ACHIEVEMENT",
    },
    guidelines: {
      CREATE_GUIDELINE: "CREATE GUIDELINE",
      UPDATE_GUIDELINE: "UPDATE GUIDELINE",
      DELETE_GUIDELINE: "DELETE GUIDELINE",
    },
    // materials: {
    //   CREATE_MATERIAL: "CREATE MATERIAL",
    //   UPDATE_MATERIAL: "UPDATE MATERIAL",
    //   DELETE_MATERIAL: "DELETE MATERIAL"
    // },
    news: {
      CREATE_NEWS: "CREATE NEWS",
      UPDATE_NEWS: "UPDATE NEWS",
      DELETE_NEWS: "DELETE NEWS",
    },
    officials: {
      CREATE_OFFICIALS: "CREATE OFFICIALS",
      UPDATE_OFFICIALS: "UPDATE OFFICIALS",
      DELETE_OFFICIALS: "DELETE OFFICIALS",
    },
    pagecontents: {
      CREATE_PAGECONTENTS: "CREATE PAGECONTENTS",
      UPDATE_PAGECONTENTS: "UPDATE PAGECONTENTS",
    },
    products: {
      CREATE_PRODUCT: "CREATE PRODUCT",
      UPDATE_PRODUCT: "UPDATE PRODUCT",
      // DELETE_PRODUCT: "DELETE PRODUCT",
    },
    records: {
      CREATE_RECORD: "CREATE RECORD",
      // UPDATE_RECORD: "UPDATE RECORD",
    },
  },
  categories: {
    CONTENT_MANAGEMENT: "CONTENT MANAGEMENT",
    AUTHENTICATION: "AUTHENTICATIon",
  },
};
